dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', dashboard, name='dashboard'),
	path('users', usersList, name='userslist'),
	path('emails', emails, name='emails'),
	path('settings', settings, name='settings'),
	path('profile', profile, name='profile'),
	path('wedding-cards', weddingCardsList, name='wedding'),
	path('birthday-cards', birthdayCardsList, name='birthday'),
	path('inauguration-cards', inaugurationcardsList, name='inauguration'),
	path('edit_card/<int:id>', editCard, name='edit_card'),
	path('videoCreation', videoCreation, name='videoCreation'),
	path('hello', helloWorld, name='hello'),
]

e_invite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('invi_cards.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# this is a comment

dashboard/models.py
from django.db import models

# Create your models here.
class Email_model(models.Model):
	email = models.EmailField()
	password = models.CharField(max_length=30)	
	status = models.CharField(max_length=2, default=1)

class sendEmails(models.Model):
	to = models.EmailField()
	subject = models.CharField(max_length=255)
	message = models.CharField(max_length=255)


class addCards(models.Model):
	image = models.ImageField(upload_to='uploads/%Y/%m/%d/image', blank=True)
	file = models.FileField(upload_to='uploads/%Y/%m/%d/jsfiles', blank=True)
	audio = models.FileField(upload_to='uploads/%Y/%m/%d/audiofiles', blank=True)
	category = models.CharField(max_length=20, blank=True)


class createdVideos(models.Model):
	output = models.FileField(upload_to='uploads/%Y/%m/%d/output_file', blank=True)
	user_rel = models.CharField(max_length=20)
		

dashboard/forms.py
from .models import *
from django.forms import *
from django import *


class Email_form(ModelForm):
	"""this module sends form"""
	password = CharField(widget=forms.PasswordInput)
	class Meta:
		model = Email_model
		fields = '__all__'

class SendMailForm(forms.ModelForm):
	message = forms.CharField(widget=forms.Textarea)
	class Meta:
		model = sendEmails
		fields = '__all__'

class CardForm(forms.ModelForm):
	file = forms.FileField(label='Add file')
	class Meta:
		model = addCards
		fields = '__all__'

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from datetime import datetime
from .forms import *
from .models import *
import os, socket
# Create your views here.

def dashboard(request):
	"""this method containing dashboard functionality"""
	video_list = createdVideos.objects.filter(user_rel=request.user.id)
	context = {
		'title': 'Dashboard',
		'videos': video_list
	}
	return render(request, 'dashboard/dashboard.html', context)

def usersList(request):
	data = User.objects.values()
	context = {
		'title': 'Users List',
		'data':data
	}
	return render(request, 'dashboard/users-list.html', context)

def cardsList(request):
	cards_data = addCards.objects.all()
	cardform = CardForm()
	if request.method == 'POST':
		cardform = CardForm(request.POST, request.FILES)
		if cardform.is_valid():
			cardform.save()
			# return HttpResponse('Card Saved Successfully')

		
	context = {
		'title': 'Cards List',
		'cardform': cardform,
		'cards_data': cards_data
		# 'cards':cards,
	}
	return render(request, 'dashboard/cards-list.html', context)

def weddingCardsList(request):
	cat_wedding ='wedding'
	id = "1"
	cards_data = addCards.objects.filter(category=cat_wedding)
	cardform = CardForm()
	if request.method == 'POST':
		cardform = CardForm(request.POST, request.FILES)
		if cardform.is_valid():
			cardform.save()
			# return HttpResponse('Card Saved Successfully')

		
	context = {
		'title': 'Wedding Cards',
		'cardform': cardform,
		'cards_data': cards_data
		# 'cards':cards,
	}
	return render(request, 'dashboard/cards/wedding_cards.html', context)

def birthdayCardsList(request):
	cat_birth = "birthday"
	cards_data = addCards.objects.filter(category=cat_birth)
	cardform = CardForm()
	if request.method == 'POST':
		cardform = CardForm(request.POST, request.FILES)
		if cardform.is_valid():
			cardform.save()
			# return HttpResponse('Card Saved Successfully')

		
	context = {
		'title': 'Birthday Cards',
		'cardform': cardform,
		'cards_data': cards_data
		# 'cards':cards,
	}
	return render(request, 'dashboard/cards/birthday_cards.html', context)

def inaugurationcardsList(request):
	cat_inaug = "inauguration"
	cards_data = addCards.objects.filter(category=cat_inaug)
	cardform = CardForm()
	if request.method == 'POST':
		cardform = CardForm(request.POST, request.FILES)
		if cardform.is_valid():
			cardform.save()
			# return HttpResponse('Card Saved Successfully')

		
	context = {
		'title': 'Inauguration Cards',
		'cardform': cardform,
		'cards_data': cards_data
		# 'cards':cards,
	}
	return render(request, 'dashboard/cards/inauguration_cards.html', context)

def editCard(request, id):
	card_data = addCards.objects.filter(id=id)
	context = {
		'title': 'Edit Card',
		'card_data': card_data
	}
	return render(request, 'dashboard/edit-card.html', context)	

def emails(request):
	send_data = SendMailForm()

	if request.method == 'POST':
		send_data = SendMailForm(request.POST)
		if send_data.is_valid():
			cred = Email_model.objects.all()

			for x in cred:
				if x.status == '1':
					usermail=x.email
					userpass=x.password
			sub = send_data.cleaned_data['subject']
			msg = send_data.cleaned_data['message']
			to = send_data.cleaned_data['to']
			from_email = usermail
			res = send_mail(sub,msg,from_email, [to], fail_silently=False,auth_user=usermail, auth_password=userpass)
			if res == True:
				send_data.save()
				messages.success(request, 'Mail sent successfully!')
				return HttpResponseRedirect('/dashboard/emails')


	data = sendEmails.objects.all()
	context = {
		'title': 'Email',
		'send_data': send_data,
		'data': data,

	}
	return render(request, 'dashboard/emails.html', context)

def settings(request):

	smtp_active_mail = Email_model.objects.filter(status=1)
	email_form = Email_form()

	if request.method == 'POST':
		
		email_form = Email_form(request.POST)
		if email_form.is_valid():
			email = email_form.cleaned_data['email']
			password = email_form.cleaned_data['password']
			smtp_active_mail.update(email=email, password=password, status=1)

	context = {
		'title': 'Settings',
		'smtp_form': email_form,
		'smtp_active_mail': smtp_active_mail
	}

	return render(request, 'dashboard/settings.html', context)
	
def profile(request):

	context = {
		'title': 'Profile'
	}
	return render(request, 'dashboard/profile.html', context)

def videoCreation(request):

	if request.method == 'POST':
		base_dir = "media/"
		path =  "card_video_file/" + request.user.username + "/"
		card_id = request.POST['card_id']
		host = "http://"+request.META['HTTP_HOST']
		extension = ".webm"
		raw_file = base_dir + path + "video_file_" + datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + extension
		output_file =  path + "output"+ datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + extension
		
		if not os.path.exists(base_dir + path):
			os.makedirs(base_dir + path)

		
		with open(raw_file, 'wb+') as destination:
			for chunk in request.FILES['blob'].chunks():
				destination.write(chunk)

		card_data = addCards.objects.filter(id=card_id)

		for x in card_data:
			audio_url = x.audio.url

		os.system("ffmpeg -i "+raw_file+" -i "+host+audio_url+" -c copy -map 0:0 -map 1:0 " + base_dir + output_file)
		vid = createdVideos(output=output_file, user_rel=request.user.id)
		vid.save()

		if os.path.isfile(raw_file):
		    os.remove(raw_file)

	data = {
		"success_data": "successfully saved"
	}

	return JsonResponse(data)

def helloWorld(func):
	print("hello")
	return func

templates/dashboard/cards-list.html
{% extends 'dashboard-base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title_content %}
	<span class="badge badge-primary float-right pointer" data-toggle="modal" data-target="#add_mail" ><i class="fas fa-plus-circle"  ></i>Add card</span>
	
{% endblock %}

{% block dash_content %}
<div class="modal fade" id="add_mail" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalCenterTitle">Add Cards</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
					<form method="post" action="" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-group">
							<div class="row">
								<div class="col">
								{{cardform.image|add_class:"form-control"|attr:"label:Add Image" }}
								</div>
							</div>
						</div>
						<div class="form-group">  
							<div class="row">
								<div class="col">
								{{cardform.file|add_class:"form-control"|attr:"label:Add File" }}

								</div>
							</div>
						</div>
						<div class="form-group">  
							<div class="row">
								<div class="col">
								{{cardform.audio|add_class:"form-control"|attr:"label:Add Audio" }}

								</div>
							</div>
						</div>
						<div class="form-group">
							<input type="hidden" name="status" id="id_status" value="0">
							<input type="submit" class="btn btn-primary" value="submit"/>
						</div>
					</form>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="container-fluid">
			<div class="row">
				{% for x in cards_data %}
				<div class="col-md-4 p-4">
					<a href="{% url 'edit_card' %}">
						<img src="{{x.image.url}}" class="img-fluid card_view pointer">
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'dashboard-base.html' %}

{% block dash_content%}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3">
			<div class="dash_card">
				<i class="fa-3x fas fa-file-alt text-success"></i>
				<p>123<span>Total Visits</span></p>
			</div>
		</div>
		<div class="col-md-3">
			<div class="dash_card">
				<i class="fa-3x fas fa-user text-primary"></i>
				<p>123<span>Total Users</span></p>
			</div>
		</div>
		<div class="col-md-3">
			<div class="dash_card">
				<i class="fa-3x fas fa-envelope text-danger"></i>
				<p>123<span>Total Mails</span></p>
			</div>
		</div>
		<div class="col-md-3">
			<div class="dash_card">
				<i class="fa-3x fas fa-exclamation-triangle text-warning"></i>
				<p>123<span>Bug Reports</span></p>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid my-3">
	<div class="row">
		{% for video in videos %}
		<div class="col-md-3">
			<a class="btn btn-success" href="{{video.output.url}}">Download card</a>
		</div>				
		{% endfor %}
	</div>
</div>
{% endblock%}

templates/dashboard/edit-card.html
{% extends 'dashboard-base.html' %}
{% block title_content %}
<span class="float-right">	
	<button id="play" class="btn btn-sm btn-info"><i class="mx-2 fas fa-play"></i>Play</button>		
	<button id="start" class="btn btn-sm btn-primary"><i class="mx-2 fas fa-video"></i>Start-recording</button>		
	<button id="download" class="btn btn-sm btn-danger"><i class="mx-2 fas fa-download"></i>Download</button>
</span>		
{% endblock %}
{% block dash_content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<canvas id="animation" width="600" height="600" ></canvas>
		</div>
		<div class="col-md-6">
			<form>
				<div class="form-group">
					<div class="row">
						<div class="col">
							<input type="text" id="first_line" name="first_line" class="form-control" value="save the date" placeholder="save the date" />
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col">
							<input type="text" id="last_line" name="last_line" class="form-control" value="save the date" placeholder="save the date" />
						</div>
					</div>
				</div>

			</form>
			<button id="update" class="btn btn-secondary">Update</button>
		</div>
	</div>
</div>
{% for x in card_data %}
	<div class="d-none" id="card_id">{{x.id}}</div>
{% endfor %}

{% endblock %}

{% block extra_script %}
	{% for x in card_data %}
	<script type="text/javascript" src="{{ x.file.url }}"></script>
	{% endfor %}
{% endblock %}

templates/dashboard/emails.html
{% extends 'dashboard-base.html' %}
{% load widget_tweaks %}

{% block title_content %}
		<span class="badge badge-primary float-right pointer" data-toggle="modal" data-target="#add_mail" ><i class="fas fa-plus-circle"  ></i>  Compose</span>
	
{% endblock %}

{% block dash_content %}
{% for message in messages %}
  <div class="alert alert-success {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
<div class="container-fluid">
	<div class="row">
		<div class="modal fade" id="add_mail" tabindex="-1" role="dialog" aria-labelledby="add_mail" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalCenterTitle">Send Mails</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
					<form method="post" action="" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-group">
							<div class="row">
								<div class="col">
									{{ send_data.to|attr:"type: email"|add_class:"form-control"|attr:"placeholder:Receiver's Address" }}		
								</div>
							</div>	
						</div>
						<div class="form-group">
							<div class="row">
								<div class="col">
									{{ send_data.subject|attr:"type: email"|add_class:"form-control"|attr:"placeholder:Subject" }}		
								</div>
							</div>	
						</div>
						<div class="form-group">
							<div class="row">
								<div class="col">
									{{ send_data.message|attr:"type: email"|add_class:"form-control"|attr:"cols:4"|attr:"rows:4" |attr:"placeholder:Message"}}		
								</div>
							</div>	
						</div>
						<input type="submit" class="btn btn-primary" value="Send">
					</form>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="col-md-12">
			
			<div class="card">
				<div class="tab">
					<button class="tablinks" onclick="tabslist(event, 'sent_mails')">Sent Mails</button>
					<button class="tablinks" onclick="tabslist(event, 'receive_mails')">Received Mails</button>
				</div>
				<!-- Tab content -->
				<div id="sent_mails" class="tabcontent" style="display: block;">
					<table class="table table-striped table-bordered email-table">
						<thead>
							<tr>
								<th>S.No.</th>
								<th>Senders</th>
								<th>Subject</th>
							</tr>
						</thead>
						<tbody>
							{% for x in data %}
								<tr>
									<td>{{x.id}}</td>
									<td>{{x.to}}</td>
									<td>{{x.subject}}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>

			<div id="receive_mails" class="tabcontent">
				<table class="table table-striped table-bordered email-table">
						<thead>
							<tr>
								<th>S.No.</th>
								<th>Receivers</th>
								<th>Subject</th>
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
			</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/dashboard/profile.html
{% extends 'dashboard-base.html' %}

{% block dash_content %}
<div class="container-fluid">
	<div class="row" >
		<div class="col-8" >
			<div class="card user_profile shadow" style="background-color: #c2d6d6;">
				<div class="card-body">
					<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">Username</label>
				</div>
				<div class="col-md-8 col-6">
					{{user.get_username}}
				</div>
			</div>
			<hr />

			<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">First Name</label>
				</div>
				<div class="col-md-8 col-6">
					{{user.first_name}}
				</div>
			</div>
			<hr />

			<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">Last Name</label>
				</div>
				<div class="col-md-8 col-6">
					{{user.last_name}}
				</div>
			</div>
			<hr />

			<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">Email Address</label>
				</div>
				<div class="col-md-8 col-6">
					{{user.email}}
				</div>
			</div>
			<hr />

			<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">User Type</label>
				</div>
				{% if user.is_superuser == True %}
				<div class="col-md-8 col-6">
					<p>Admin</p>
				</div>
				{% else %}
				<div class="col-md-8 col-6">
					<p>Subscriber</p>
				</div>
				{% endif %}
			</div>
			<hr />

			<div class="row">
				<div class="col-sm-5 col-md-4 col-7">
					<label style="font-weight:bold;">Mobile</label>
				</div>
				<div class="col-md-8 col-6">
					
				</div>
			</div>
			<hr />
					
				</div>
			</div>			
		</div>	
	</div>
</div>

{% endblock %}

templates/dashboard/settings.html
{% extends 'dashboard-base.html' %}
{% load widget_tweaks %}
{% block dash_content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<div class="card-title border-bottom mb-3"><strong>SMTP Mails</strong> 
						<span class="float-right pointer"  data-toggle="modal" data-target="#add_mail">
							<i class="fas fa-pen-square mx-1"></i>
							edit
						</span>
					</div>
					{% for smtp in smtp_active_mail %}
						{{smtp.email}}
						{% if smtp.status == '1' %}
						<span class="float-right badge badge-success p-2">
							active
						</span>
						{% endif %}
						
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Modal -->
		<div class="modal fade" id="add_mail" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalCenterTitle">Edit Credentials</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
				<div class="card shadow">
					<div class="card-body">
					<div class="card-title mb-3 border-bottom">SMTP host setup</div>
					<form method="post" action="" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-group">
							<div class="row">
								<div class="col">
								{{ smtp_form.email|attr:"type: email"|add_class:"form-control"|attr:"placeholder:Enter Email Address" }}
								</div>
							</div>
						</div>
						<div class="form-group">  
							<div class="row">
								<div class="col">
								{{ smtp_form.password|add_class:"form-control"|attr:"placeholder:Enter password" }}
								</div>
							</div>
						</div>
						<div class="form-group">
							<input type="hidden" name="status" id="id_status" value="1">
							<input type="submit" class="btn btn-primary" value="submit"/>
						</div>
					</form>
					</div>
				</div>
		      </div>
		    </div>
		  </div>
		</div>
		
	</div>
</div>

{% endblock %}

templates/dashboard/users-list.html
{% extends 'dashboard-base.html' %}
{% block dash_content%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card p-3 shadow">
        <div class="card-body">
          <table class="table table-striped table-bordered myTable">
            <thead>
              <tr>
                <th scope="col">S.no</th>
                <th scope="col">Username</th>
                <th scope="col">Email id</th>
                <th scope="col">User type</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for x in data %}
              <tr>
                <th scope="row">{{x.id}}</th>
                <td>{{x.username}}</td>
                <td>{{x.email}}</td>
                <td>
                  {% if x.is_superuser == True %}
                    Admin
                  {% else %}
                    Subscriber
                  {% endif %}
                </td>

                <td class="text-center">
                  {% if x.is_active == True %}
                    <!-- <i class="fas fa-1x  fa-toggle-on"></i> --> Active
                  {% else %}
                    <!-- <i class="fas fa-1x  fa-toggle-off"></i> --> Inactive
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}